spring:
  data:
    mongodb:
      uri: mongodb+srv://blogger:VmqdFefidA4LHun@cluster0.8bn1n.mongodb.net/cloud-base?authSource=admin&replicaSet=atlas-glimny-shard-0&readPreference=primary&ssl=true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jeff@126
    url: jdbc:mysql://localhost:3306/console-mall?characterEncoding=utf8mb4&serverTimezone=GMT%2B8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  type-aliases-package: me.jeffrey.open.dto